//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace SDK_Test.SIRE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlphaCorpConnectorBinding", Namespace="urn:AlphaCorpConnector")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(KeyMapping))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Motion))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AttendeeStatus))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Rollcall))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(VoteRecord))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(VoteEntry))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Note))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Document))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ItemDetail))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AgendaItem))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MetaRecordBase))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ViewData))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Camera))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MetaData))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ClipData))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FolderData))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Attendee))]
    public partial class AlphaCorpConnectorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback logMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFoldersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getArchivesByForeignIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback createEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback writeEventMetaBranchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEventMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getArchiveMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback setArchiveMinutesURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback setEventAgendaURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCamerasOperationCompleted;
        
        private System.Threading.SendOrPostCallback getViewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setViewForeignIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getViewsByForeignIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback sanitizeHtmlTestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AlphaCorpConnectorService() {
            this.Url = global::SDK_Test.Properties.Settings.Default.SDK_Test_SIRE_AlphaCorpConnectorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event logMessageCompletedEventHandler logMessageCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event getEventsCompletedEventHandler getEventsCompleted;
        
        /// <remarks/>
        public event getFoldersCompletedEventHandler getFoldersCompleted;
        
        /// <remarks/>
        public event getArchivesByForeignIDCompletedEventHandler getArchivesByForeignIDCompleted;
        
        /// <remarks/>
        public event createEventCompletedEventHandler createEventCompleted;
        
        /// <remarks/>
        public event writeEventMetaBranchCompletedEventHandler writeEventMetaBranchCompleted;
        
        /// <remarks/>
        public event getEventMetaDataCompletedEventHandler getEventMetaDataCompleted;
        
        /// <remarks/>
        public event getArchiveMetaDataCompletedEventHandler getArchiveMetaDataCompleted;
        
        /// <remarks/>
        public event setArchiveMinutesURLCompletedEventHandler setArchiveMinutesURLCompleted;
        
        /// <remarks/>
        public event setEventAgendaURLCompletedEventHandler setEventAgendaURLCompleted;
        
        /// <remarks/>
        public event getCamerasCompletedEventHandler getCamerasCompleted;
        
        /// <remarks/>
        public event getViewsCompletedEventHandler getViewsCompleted;
        
        /// <remarks/>
        public event setViewForeignIDCompletedEventHandler setViewForeignIDCompleted;
        
        /// <remarks/>
        public event getViewsByForeignIDCompletedEventHandler getViewsByForeignIDCompleted;
        
        /// <remarks/>
        public event sanitizeHtmlTestCompletedEventHandler sanitizeHtmlTestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#logMessage", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public int logMessage(string message, string @class, int priority) {
            object[] results = this.Invoke("logMessage", new object[] {
                        message,
                        @class,
                        priority});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void logMessageAsync(string message, string @class, int priority) {
            this.logMessageAsync(message, @class, priority, null);
        }
        
        /// <remarks/>
        public void logMessageAsync(string message, string @class, int priority, object userState) {
            if ((this.logMessageOperationCompleted == null)) {
                this.logMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogMessageOperationCompleted);
            }
            this.InvokeAsync("logMessage", new object[] {
                        message,
                        @class,
                        priority}, this.logMessageOperationCompleted, userState);
        }
        
        private void OnlogMessageOperationCompleted(object arg) {
            if ((this.logMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logMessageCompleted(this, new logMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#login", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public int login(string username, string password) {
            object[] results = this.Invoke("login", new object[] {
                        username,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string username, string password) {
            this.loginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void loginAsync(string username, string password, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        username,
                        password}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#getEvents", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("events")]
        public EventData[] getEvents() {
            object[] results = this.Invoke("getEvents", new object[0]);
            return ((EventData[])(results[0]));
        }
        
        /// <remarks/>
        public void getEventsAsync() {
            this.getEventsAsync(null);
        }
        
        /// <remarks/>
        public void getEventsAsync(object userState) {
            if ((this.getEventsOperationCompleted == null)) {
                this.getEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEventsOperationCompleted);
            }
            this.InvokeAsync("getEvents", new object[0], this.getEventsOperationCompleted, userState);
        }
        
        private void OngetEventsOperationCompleted(object arg) {
            if ((this.getEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEventsCompleted(this, new getEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#getFolders", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("folders")]
        public FolderData[] getFolders() {
            object[] results = this.Invoke("getFolders", new object[0]);
            return ((FolderData[])(results[0]));
        }
        
        /// <remarks/>
        public void getFoldersAsync() {
            this.getFoldersAsync(null);
        }
        
        /// <remarks/>
        public void getFoldersAsync(object userState) {
            if ((this.getFoldersOperationCompleted == null)) {
                this.getFoldersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFoldersOperationCompleted);
            }
            this.InvokeAsync("getFolders", new object[0], this.getFoldersOperationCompleted, userState);
        }
        
        private void OngetFoldersOperationCompleted(object arg) {
            if ((this.getFoldersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFoldersCompleted(this, new getFoldersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#getArchivesByForeignID", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("archives")]
        public ClipData[] getArchivesByForeignID(int ForeignID) {
            object[] results = this.Invoke("getArchivesByForeignID", new object[] {
                        ForeignID});
            return ((ClipData[])(results[0]));
        }
        
        /// <remarks/>
        public void getArchivesByForeignIDAsync(int ForeignID) {
            this.getArchivesByForeignIDAsync(ForeignID, null);
        }
        
        /// <remarks/>
        public void getArchivesByForeignIDAsync(int ForeignID, object userState) {
            if ((this.getArchivesByForeignIDOperationCompleted == null)) {
                this.getArchivesByForeignIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetArchivesByForeignIDOperationCompleted);
            }
            this.InvokeAsync("getArchivesByForeignID", new object[] {
                        ForeignID}, this.getArchivesByForeignIDOperationCompleted, userState);
        }
        
        private void OngetArchivesByForeignIDOperationCompleted(object arg) {
            if ((this.getArchivesByForeignIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getArchivesByForeignIDCompleted(this, new getArchivesByForeignIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#createEvent", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("EventID")]
        public int createEvent(EventData Event) {
            object[] results = this.Invoke("createEvent", new object[] {
                        Event});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void createEventAsync(EventData Event) {
            this.createEventAsync(Event, null);
        }
        
        /// <remarks/>
        public void createEventAsync(EventData Event, object userState) {
            if ((this.createEventOperationCompleted == null)) {
                this.createEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateEventOperationCompleted);
            }
            this.InvokeAsync("createEvent", new object[] {
                        Event}, this.createEventOperationCompleted, userState);
        }
        
        private void OncreateEventOperationCompleted(object arg) {
            if ((this.createEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createEventCompleted(this, new createEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#writeEventMetaBranch", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("KeyTable")]
        public KeyMapping[] writeEventMetaBranch(int EventID, int ParentID, MetaData[] Branch) {
            object[] results = this.Invoke("writeEventMetaBranch", new object[] {
                        EventID,
                        ParentID,
                        Branch});
            return ((KeyMapping[])(results[0]));
        }
        
        /// <remarks/>
        public void writeEventMetaBranchAsync(int EventID, int ParentID, MetaData[] Branch) {
            this.writeEventMetaBranchAsync(EventID, ParentID, Branch, null);
        }
        
        /// <remarks/>
        public void writeEventMetaBranchAsync(int EventID, int ParentID, MetaData[] Branch, object userState) {
            if ((this.writeEventMetaBranchOperationCompleted == null)) {
                this.writeEventMetaBranchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwriteEventMetaBranchOperationCompleted);
            }
            this.InvokeAsync("writeEventMetaBranch", new object[] {
                        EventID,
                        ParentID,
                        Branch}, this.writeEventMetaBranchOperationCompleted, userState);
        }
        
        private void OnwriteEventMetaBranchOperationCompleted(object arg) {
            if ((this.writeEventMetaBranchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.writeEventMetaBranchCompleted(this, new writeEventMetaBranchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#getEventMetaData", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("metadata")]
        public MetaData[] getEventMetaData(int EventID) {
            object[] results = this.Invoke("getEventMetaData", new object[] {
                        EventID});
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getEventMetaDataAsync(int EventID) {
            this.getEventMetaDataAsync(EventID, null);
        }
        
        /// <remarks/>
        public void getEventMetaDataAsync(int EventID, object userState) {
            if ((this.getEventMetaDataOperationCompleted == null)) {
                this.getEventMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEventMetaDataOperationCompleted);
            }
            this.InvokeAsync("getEventMetaData", new object[] {
                        EventID}, this.getEventMetaDataOperationCompleted, userState);
        }
        
        private void OngetEventMetaDataOperationCompleted(object arg) {
            if ((this.getEventMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEventMetaDataCompleted(this, new getEventMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#getArchiveMetaData", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("metadata")]
        public MetaData[] getArchiveMetaData(int ClipID) {
            object[] results = this.Invoke("getArchiveMetaData", new object[] {
                        ClipID});
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getArchiveMetaDataAsync(int ClipID) {
            this.getArchiveMetaDataAsync(ClipID, null);
        }
        
        /// <remarks/>
        public void getArchiveMetaDataAsync(int ClipID, object userState) {
            if ((this.getArchiveMetaDataOperationCompleted == null)) {
                this.getArchiveMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetArchiveMetaDataOperationCompleted);
            }
            this.InvokeAsync("getArchiveMetaData", new object[] {
                        ClipID}, this.getArchiveMetaDataOperationCompleted, userState);
        }
        
        private void OngetArchiveMetaDataOperationCompleted(object arg) {
            if ((this.getArchiveMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getArchiveMetaDataCompleted(this, new getArchiveMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#setArchiveMinutesURL", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        public void setArchiveMinutesURL(int ClipID, string URL) {
            this.Invoke("setArchiveMinutesURL", new object[] {
                        ClipID,
                        URL});
        }
        
        /// <remarks/>
        public void setArchiveMinutesURLAsync(int ClipID, string URL) {
            this.setArchiveMinutesURLAsync(ClipID, URL, null);
        }
        
        /// <remarks/>
        public void setArchiveMinutesURLAsync(int ClipID, string URL, object userState) {
            if ((this.setArchiveMinutesURLOperationCompleted == null)) {
                this.setArchiveMinutesURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetArchiveMinutesURLOperationCompleted);
            }
            this.InvokeAsync("setArchiveMinutesURL", new object[] {
                        ClipID,
                        URL}, this.setArchiveMinutesURLOperationCompleted, userState);
        }
        
        private void OnsetArchiveMinutesURLOperationCompleted(object arg) {
            if ((this.setArchiveMinutesURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setArchiveMinutesURLCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#setEventAgendaURL", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        public void setEventAgendaURL(int EventID, string URL) {
            this.Invoke("setEventAgendaURL", new object[] {
                        EventID,
                        URL});
        }
        
        /// <remarks/>
        public void setEventAgendaURLAsync(int EventID, string URL) {
            this.setEventAgendaURLAsync(EventID, URL, null);
        }
        
        /// <remarks/>
        public void setEventAgendaURLAsync(int EventID, string URL, object userState) {
            if ((this.setEventAgendaURLOperationCompleted == null)) {
                this.setEventAgendaURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetEventAgendaURLOperationCompleted);
            }
            this.InvokeAsync("setEventAgendaURL", new object[] {
                        EventID,
                        URL}, this.setEventAgendaURLOperationCompleted, userState);
        }
        
        private void OnsetEventAgendaURLOperationCompleted(object arg) {
            if ((this.setEventAgendaURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setEventAgendaURLCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#getCameras", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("Cameras")]
        public Camera[] getCameras() {
            object[] results = this.Invoke("getCameras", new object[0]);
            return ((Camera[])(results[0]));
        }
        
        /// <remarks/>
        public void getCamerasAsync() {
            this.getCamerasAsync(null);
        }
        
        /// <remarks/>
        public void getCamerasAsync(object userState) {
            if ((this.getCamerasOperationCompleted == null)) {
                this.getCamerasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCamerasOperationCompleted);
            }
            this.InvokeAsync("getCameras", new object[0], this.getCamerasOperationCompleted, userState);
        }
        
        private void OngetCamerasOperationCompleted(object arg) {
            if ((this.getCamerasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCamerasCompleted(this, new getCamerasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#getViews", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("Views")]
        public ViewData[] getViews() {
            object[] results = this.Invoke("getViews", new object[0]);
            return ((ViewData[])(results[0]));
        }
        
        /// <remarks/>
        public void getViewsAsync() {
            this.getViewsAsync(null);
        }
        
        /// <remarks/>
        public void getViewsAsync(object userState) {
            if ((this.getViewsOperationCompleted == null)) {
                this.getViewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetViewsOperationCompleted);
            }
            this.InvokeAsync("getViews", new object[0], this.getViewsOperationCompleted, userState);
        }
        
        private void OngetViewsOperationCompleted(object arg) {
            if ((this.getViewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getViewsCompleted(this, new getViewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#setViewForeignID", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        public void setViewForeignID(int ViewID, int ForeignID) {
            this.Invoke("setViewForeignID", new object[] {
                        ViewID,
                        ForeignID});
        }
        
        /// <remarks/>
        public void setViewForeignIDAsync(int ViewID, int ForeignID) {
            this.setViewForeignIDAsync(ViewID, ForeignID, null);
        }
        
        /// <remarks/>
        public void setViewForeignIDAsync(int ViewID, int ForeignID, object userState) {
            if ((this.setViewForeignIDOperationCompleted == null)) {
                this.setViewForeignIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetViewForeignIDOperationCompleted);
            }
            this.InvokeAsync("setViewForeignID", new object[] {
                        ViewID,
                        ForeignID}, this.setViewForeignIDOperationCompleted, userState);
        }
        
        private void OnsetViewForeignIDOperationCompleted(object arg) {
            if ((this.setViewForeignIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setViewForeignIDCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#getViewsByForeignID", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("Views")]
        public ViewData[] getViewsByForeignID(int ForeignID) {
            object[] results = this.Invoke("getViewsByForeignID", new object[] {
                        ForeignID});
            return ((ViewData[])(results[0]));
        }
        
        /// <remarks/>
        public void getViewsByForeignIDAsync(int ForeignID) {
            this.getViewsByForeignIDAsync(ForeignID, null);
        }
        
        /// <remarks/>
        public void getViewsByForeignIDAsync(int ForeignID, object userState) {
            if ((this.getViewsByForeignIDOperationCompleted == null)) {
                this.getViewsByForeignIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetViewsByForeignIDOperationCompleted);
            }
            this.InvokeAsync("getViewsByForeignID", new object[] {
                        ForeignID}, this.getViewsByForeignIDOperationCompleted, userState);
        }
        
        private void OngetViewsByForeignIDOperationCompleted(object arg) {
            if ((this.getViewsByForeignIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getViewsByForeignIDCompleted(this, new getViewsByForeignIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AlphaCorpConnector#AlphaCorpConnector#sanitizeHtmlTest", RequestNamespace="urn:AlphaCorpConnector", ResponseNamespace="urn:AlphaCorpConnector")]
        [return: System.Xml.Serialization.SoapElementAttribute("Text")]
        public string sanitizeHtmlTest(string Html) {
            object[] results = this.Invoke("sanitizeHtmlTest", new object[] {
                        Html});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sanitizeHtmlTestAsync(string Html) {
            this.sanitizeHtmlTestAsync(Html, null);
        }
        
        /// <remarks/>
        public void sanitizeHtmlTestAsync(string Html, object userState) {
            if ((this.sanitizeHtmlTestOperationCompleted == null)) {
                this.sanitizeHtmlTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsanitizeHtmlTestOperationCompleted);
            }
            this.InvokeAsync("sanitizeHtmlTest", new object[] {
                        Html}, this.sanitizeHtmlTestOperationCompleted, userState);
        }
        
        private void OnsanitizeHtmlTestOperationCompleted(object arg) {
            if ((this.sanitizeHtmlTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sanitizeHtmlTestCompleted(this, new sanitizeHtmlTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class EventData {
        
        private int idField;
        
        private int foreignIDField;
        
        private string nameField;
        
        private int cameraIDField;
        
        private int folderIDField;
        
        private int durationField;
        
        private System.DateTime startTimeField;
        
        private Attendee[] attendeesField;
        
        private string[] motionTypesField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string agendaTitleField;
        
        private System.DateTime meetingTimeField;
        
        private System.DateTime agendaPostedDateField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ForeignID {
            get {
                return this.foreignIDField;
            }
            set {
                this.foreignIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int CameraID {
            get {
                return this.cameraIDField;
            }
            set {
                this.cameraIDField = value;
            }
        }
        
        /// <remarks/>
        public int FolderID {
            get {
                return this.folderIDField;
            }
            set {
                this.folderIDField = value;
            }
        }
        
        /// <remarks/>
        public int Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public Attendee[] Attendees {
            get {
                return this.attendeesField;
            }
            set {
                this.attendeesField = value;
            }
        }
        
        /// <remarks/>
        public string[] MotionTypes {
            get {
                return this.motionTypesField;
            }
            set {
                this.motionTypesField = value;
            }
        }
        
        /// <remarks/>
        public string Street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        public string Street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string AgendaTitle {
            get {
                return this.agendaTitleField;
            }
            set {
                this.agendaTitleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MeetingTime {
            get {
                return this.meetingTimeField;
            }
            set {
                this.meetingTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AgendaPostedDate {
            get {
                return this.agendaPostedDateField;
            }
            set {
                this.agendaPostedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class Attendee {
        
        private string nameField;
        
        private bool votingField;
        
        private bool chairField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool Voting {
            get {
                return this.votingField;
            }
            set {
                this.votingField = value;
            }
        }
        
        /// <remarks/>
        public bool Chair {
            get {
                return this.chairField;
            }
            set {
                this.chairField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class KeyMapping {
        
        private int foreignIDField;
        
        private int granicusIDField;
        
        /// <remarks/>
        public int ForeignID {
            get {
                return this.foreignIDField;
            }
            set {
                this.foreignIDField = value;
            }
        }
        
        /// <remarks/>
        public int GranicusID {
            get {
                return this.granicusIDField;
            }
            set {
                this.granicusIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class Motion {
        
        private string moverField;
        
        private string seconderField;
        
        private string typeField;
        
        private string motionTextField;
        
        /// <remarks/>
        public string Mover {
            get {
                return this.moverField;
            }
            set {
                this.moverField = value;
            }
        }
        
        /// <remarks/>
        public string Seconder {
            get {
                return this.seconderField;
            }
            set {
                this.seconderField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string MotionText {
            get {
                return this.motionTextField;
            }
            set {
                this.motionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class AttendeeStatus {
        
        private string nameField;
        
        private int statusField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class Rollcall {
        
        private AttendeeStatus[] attendeesField;
        
        /// <remarks/>
        public AttendeeStatus[] Attendees {
            get {
                return this.attendeesField;
            }
            set {
                this.attendeesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class VoteRecord {
        
        private int motionIDField;
        
        private bool passedField;
        
        private VoteEntry[] votesField;
        
        /// <remarks/>
        public int MotionID {
            get {
                return this.motionIDField;
            }
            set {
                this.motionIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Passed {
            get {
                return this.passedField;
            }
            set {
                this.passedField = value;
            }
        }
        
        /// <remarks/>
        public VoteEntry[] Votes {
            get {
                return this.votesField;
            }
            set {
                this.votesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class VoteEntry {
        
        private string nameField;
        
        private int voteField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Vote {
            get {
                return this.voteField;
            }
            set {
                this.voteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class Note {
        
        private string noteTextField;
        
        private string editorsNotesField;
        
        private bool privateField;
        
        /// <remarks/>
        public string NoteText {
            get {
                return this.noteTextField;
            }
            set {
                this.noteTextField = value;
            }
        }
        
        /// <remarks/>
        public string EditorsNotes {
            get {
                return this.editorsNotesField;
            }
            set {
                this.editorsNotesField = value;
            }
        }
        
        /// <remarks/>
        public bool Private {
            get {
                return this.privateField;
            }
            set {
                this.privateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class Document {
        
        private string descriptionField;
        
        private string locationField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class ItemDetail {
        
        private int keyField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        public int Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class AgendaItem {
        
        private ItemDetail[] detailsField;
        
        private string departmentField;
        
        private string actionsField;
        
        /// <remarks/>
        public ItemDetail[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class MetaRecordBase {
        
        private string payload1Field;
        
        private string payload2Field;
        
        private string ref1Field;
        
        private string ref2Field;
        
        private int ref3Field;
        
        /// <remarks/>
        public string Payload1 {
            get {
                return this.payload1Field;
            }
            set {
                this.payload1Field = value;
            }
        }
        
        /// <remarks/>
        public string Payload2 {
            get {
                return this.payload2Field;
            }
            set {
                this.payload2Field = value;
            }
        }
        
        /// <remarks/>
        public string Ref1 {
            get {
                return this.ref1Field;
            }
            set {
                this.ref1Field = value;
            }
        }
        
        /// <remarks/>
        public string Ref2 {
            get {
                return this.ref2Field;
            }
            set {
                this.ref2Field = value;
            }
        }
        
        /// <remarks/>
        public int Ref3 {
            get {
                return this.ref3Field;
            }
            set {
                this.ref3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class ViewData {
        
        private int idField;
        
        private int foreignIDField;
        
        private string nameField;
        
        private bool isActiveField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ForeignID {
            get {
                return this.foreignIDField;
            }
            set {
                this.foreignIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class Camera {
        
        private int idField;
        
        private string typeField;
        
        private string nameField;
        
        private string internalIPField;
        
        private string externalIPField;
        
        private int broadcastPortField;
        
        private int controlPortField;
        
        private string identifierField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string InternalIP {
            get {
                return this.internalIPField;
            }
            set {
                this.internalIPField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalIP {
            get {
                return this.externalIPField;
            }
            set {
                this.externalIPField = value;
            }
        }
        
        /// <remarks/>
        public int BroadcastPort {
            get {
                return this.broadcastPortField;
            }
            set {
                this.broadcastPortField = value;
            }
        }
        
        /// <remarks/>
        public int ControlPort {
            get {
                return this.controlPortField;
            }
            set {
                this.controlPortField = value;
            }
        }
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class MetaData {
        
        private int idField;
        
        private int parentIDField;
        
        private int foreignIDField;
        
        private string typeField;
        
        private string nameField;
        
        private int timeStampField;
        
        private object payloadField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        public int ForeignID {
            get {
                return this.foreignIDField;
            }
            set {
                this.foreignIDField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public object Payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class ClipData {
        
        private int idField;
        
        private int foreignIDField;
        
        private string nameField;
        
        private int cameraIDField;
        
        private int durationField;
        
        private System.DateTime startTimeField;
        
        private Attendee[] attendeesField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string agendaTitleField;
        
        private System.DateTime agendaPostedDateField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ForeignID {
            get {
                return this.foreignIDField;
            }
            set {
                this.foreignIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int CameraID {
            get {
                return this.cameraIDField;
            }
            set {
                this.cameraIDField = value;
            }
        }
        
        /// <remarks/>
        public int Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public Attendee[] Attendees {
            get {
                return this.attendeesField;
            }
            set {
                this.attendeesField = value;
            }
        }
        
        /// <remarks/>
        public string Street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        public string Street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string AgendaTitle {
            get {
                return this.agendaTitleField;
            }
            set {
                this.agendaTitleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AgendaPostedDate {
            get {
                return this.agendaPostedDateField;
            }
            set {
                this.agendaPostedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://granicus.com/xsd")]
    public partial class FolderData {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private int playerTemplateIDField;
        
        private System.DateTime createdDateField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int PlayerTemplateID {
            get {
                return this.playerTemplateIDField;
            }
            set {
                this.playerTemplateIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void logMessageCompletedEventHandler(object sender, logMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getEventsCompletedEventHandler(object sender, getEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EventData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EventData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getFoldersCompletedEventHandler(object sender, getFoldersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFoldersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFoldersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getArchivesByForeignIDCompletedEventHandler(object sender, getArchivesByForeignIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getArchivesByForeignIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getArchivesByForeignIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClipData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClipData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void createEventCompletedEventHandler(object sender, createEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void writeEventMetaBranchCompletedEventHandler(object sender, writeEventMetaBranchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class writeEventMetaBranchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal writeEventMetaBranchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyMapping[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyMapping[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getEventMetaDataCompletedEventHandler(object sender, getEventMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEventMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEventMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getArchiveMetaDataCompletedEventHandler(object sender, getArchiveMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getArchiveMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getArchiveMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setArchiveMinutesURLCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setEventAgendaURLCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getCamerasCompletedEventHandler(object sender, getCamerasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCamerasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCamerasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Camera[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Camera[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getViewsCompletedEventHandler(object sender, getViewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getViewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getViewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViewData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViewData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setViewForeignIDCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getViewsByForeignIDCompletedEventHandler(object sender, getViewsByForeignIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getViewsByForeignIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getViewsByForeignIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViewData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViewData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void sanitizeHtmlTestCompletedEventHandler(object sender, sanitizeHtmlTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sanitizeHtmlTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sanitizeHtmlTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591